Crystel/Areas/Agent/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crystel.Areas.Agent.Controllers
{
    public class ScheduleController : Controller
    {
        // GET: Agent/Schedule
        public ActionResult ScheduleList()
        {
            return View();
        }
    }
}

Crystel/Areas/HR/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DataAccsess.Entity;
using Newtonsoft.Json;

namespace Crystel.Areas.HR.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: HR/Department
        public ActionResult NewDepartment()
        {
            return View();
        }
        public async Task<ActionResult> DepartmentList()
        {
            vmDepartment vm = new vmDepartment();
            List<Department> DeptList = new List<Department>();
            string ApiUrl = "http://localhost/CrystelWebApi/api/Department/MainDept";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(ApiUrl);
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responseMessage = await client.GetAsync(ApiUrl);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                DeptList = JsonConvert.DeserializeObject<List<Department>>(responseData);
            }
            vm.Dept = DeptList;
            return View("DepartmentList",vm);
            
        }
        public ActionResult Update(int id)
        {
            ViewData["Id"] = id;
            return View("NewDepartment");
        }
    }
}

Crystel/Areas/HR/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crystel.Areas.HR.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: HR/Employee
        public ActionResult NewEmployee()
        {
            return View();
        }
       
    }
}

Crystel/Areas/HR/Controllers/JobTitleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using DataAccsess.Entity;
using System.Net.Http;
using Newtonsoft.Json;

namespace Crystel.Areas.HR.Controllers
{
    public class JobTitleController : Controller
    {
        // GET: HR/JobTitle
        public ActionResult NewJobTitle()
        {
            return View();
        }
        public async Task<ActionResult> JobTitlelist()
        {
            vmJob vm = new vmJob();
            List<Job_Title> JobList = new List<Job_Title>();
            string ApiUrl = "http://localhost/CrystelWebApi/api/JobTitle/MainJob";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(ApiUrl);
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responseMessage = await client.GetAsync(ApiUrl);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                JobList = JsonConvert.DeserializeObject<List<Job_Title>>(responseData);
            }
            vm.jobs = JobList;
            return View("JobTitlelist", vm);
        }
        public ActionResult Update(int id)
        {
            ViewData["Id"] = id;
            return View("NewJobTitle");
        }
    }
}

Crystel/Areas/HR/Controllers/ProjectController.cs
using DataAccsess.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Crystel.Areas.HR.Controllers
{
    public class ProjectController : Controller
    {
        // GET: HR/Project
        public ActionResult ProjectName()
        {
            return View();
        }
        public async Task<ActionResult> ProjectList()
        {
            vmProject vm = new vmProject();
            List<ProjectName> ProjectList = new List<ProjectName>();
            string ApiUrl = "http://localhost/CrystelWebApi/api/Project/MainProject";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(ApiUrl);
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responseMessage = await client.GetAsync(ApiUrl);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                ProjectList = JsonConvert.DeserializeObject<List<ProjectName>>(responseData);
            }
            vm.projects = ProjectList;
            return View("ProjectList", vm);
        }
        public ActionResult Update(int id)
        {
            ViewData["Id"] = id;
            return View("ProjectName");
        }
    }
}

Crystel/Areas/Login/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crystel.Areas.Login.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login/Login
        public ActionResult Login()
        {
            return View();
        }
    }
}

Crystel/Areas/Senior/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crystel.Areas.Senior.Controllers
{
    public class AgentsController : Controller
    {
        // GET: Senior/Agents
        public ActionResult NewAgents()
        {
            return View();
        }
    }
}

Crystel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crystel.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Crystel/Areas/Agent/Views/Schedule/ScheduleList.cshtml
@{
    ViewBag.Title = "ScheduleList";
    Layout = "~/Areas/Agent/Views/Shared/_agent.cshtml";
}

<h2>ScheduleList</h2>

Crystel/Areas/Agent/Views/Shared/_agent.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style type="text/css">
        input {
            padding: 10px;
            font-family: FontAwesome, "Open Sans", Verdana, sans-serif;
            font-style: normal;
            font-weight: normal;
            text-decoration: inherit;
        }
    </style>
    <link rel="icon" href="~/Image/crystel_social.jpg">
    <!--Styles-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="~/StyleCrystel/css/bootstrap.min.css" rel="stylesheet" />
    <link href='//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css' rel='stylesheet'>
    <link href="~/StyleCrystel/css/animate.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/themify-icons.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/flaticon.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/slick.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/style.css" rel="stylesheet" />
    <script src="~/StyleCrystel/js/jquery-1.12.1.min.js"></script>
    <script src="~/StyleCrystel/js/bootstrap.min.js"></script>
    <script src="~/StyleCrystel/js/popper.min.js"></script>
    <script src="~/StyleCrystel/js/jquery.magnific-popup.js"></script>
    <script src="~/StyleCrystel/js/swiper.min.js"></script>
    <script src="~/StyleCrystel/js/masonry.pkgd.js"></script>
    <script src="~/StyleCrystel/js/owl.carousel.min.js"></script>
    <script src="~/StyleCrystel/js/slick.min.js"></script>
    <script src="~/StyleCrystel/js/custom.js"></script>
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <title>@ViewBag.Title - Crystel</title>
    @RenderSection("Head", false)
</head>
<body>
    <div class="container">
        <header class="main_menu">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <a class="navbar-brand" href="index.html">
                                <img src="~/Image/logo.png" alt="logo" width="220" height="50" />
                            </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse main-menu-item justify-content-end"
                                 id="navbarSupportedContent">
                                <ul class="navbar-nav">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="index.html">Home </a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Create
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="project.html">New Employee</a>
                                            <a class="dropdown-item" href="project_details.html">New Department</a>
                                            <a class="dropdown-item" href="service.html">New Job Title</a>
                                            <a class="dropdown-item" href="elements.html">New Project Name</a>
                                        </div>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Manage
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="project.html">Employees</a>
                                            <a class="dropdown-item" href="project_details.html">Departments</a>
                                            <a class="dropdown-item" href="service.html">Job Titles</a>
                                            <a class="dropdown-item" href="elements.html">Projects</a>
                                        </div>
                                    </li>
                                    <li class="nav-item active">
                                        <a class="nav-link" href="contact.html">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </header>
    </div>

    @RenderSection("Body")
</body>
</html>

Crystel/Areas/HR/Views/Department/DepartmentList.cshtml
@model DataAccsess.Entity.vmDepartment
@{
    ViewBag.Title = "DepartmentList";
    Layout = "~/Areas/HR/Views/Shared/View.cshtml";
}
@section Head{

    <script type="text/javascript">
         function Update(id) {
            debugger;
            window.location = '@Url.Action("Update/Id", "Department")'.replace("Id", id)
        }

        $(document).ready(function () {
            $('#DeptTable').DataTable({
                "ajax": {
                    "url": "",
                    "type": "GET",
                    "datatype":"json"
                },

            });
        });
    </script>

    }

@section Body{
    <div class="container x_panel">
        <div class="row">
            <div class="col-lg-5">
                <h4 style="color:#ff6a00">Department List</h4>
            </div>
        </div>
        <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
        <br />
        <div class="x_title"></div>
        <div class="x_panel">
            <div class="container-fluid">
                <div class="form-group">
                    <table class="table" id="DeptTable">
                        <thead style="background-color:white ; color:#ff6a00;border-color:#ff6a00">
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var x = from a in Model.Dept
                                        select a;
                            }
                            @foreach (var y in x)
                            {
                                <tr>
                                    <th scope="row">@y.Name</th>
                                    <td align="right">
                                        <button type="button" class="btn btn-danger" onclick="del(@y.Id)">Delete</button>
                                    </td>
                                    <td align="right">
                                        <button type="button" class="btn btn-warning" onclick="Update(@y.Id)">Edit</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                    <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
                </div>
            </div>
        </div>
    </div>
}

Crystel/Areas/HR/Views/Department/NewDepartment.cshtml
@{
    ViewBag.Title = "NewDepartment";
    Layout = "~/Areas/HR/Views/Shared/View.cshtml";
}
@section Head{
    <script type="text/javascript">
    $(document).ready(function () {
            debugger;
            var Id = @ViewData["Id"];
            if (Id != 0) {
                $('#btnSave').text("Update")
                $('#hDept').text("Edit Department")
                $.ajax({
                    type: 'Get',
                    url: '/CrystelWebApi/api/Department/Load?Id=' + Id,
                    contentType: 'application/json;charset=utf-8',
                    dataType: 'json',
                    data: '{}',
                    success: function (data) {
                        $('#txtDept').val(data.Name);
                    }
                })
            }
            $('#btnSave').click(function () {
                debugger;
                var Id = @ViewData["Id"];
                if (Id != 0) {
                    var name = $("#txtDept").val();
                    var data = {
                        'Id': Id,
                    'Name': name,
                }
                    $.ajax({
                        type: 'post',
                        url: '/CrystelWebApi/api/Department/Update',
                        contentType: 'application/json;charset=utf-8',
                        data: JSON.stringify(data),
                        dataType: 'json',
                        success: function () {
                            alert("Updated")
                        },
                        error: function (error) {
                            alert(error.responseText);
                            alert('there is error');
                        }


                    })
                }
                else {
                    var name = $("#txtDept").val();
                    var data = {
                        'Name': name,
                    }
                    $.ajax({
                        type: 'Post',
                        url: '/CrystelWebApi/api/Department/Save',
                        contentType: 'application/json;charset=utf-8',
                        data: JSON.stringify(data),
                        dataType: 'json',
                        success: function () {
                            alert("Saved")
                        },
                        error: function (error) {
                            alert(error.responseText);
                            alert('there is error');
                        }


                    })
                }

            })

        });
    </script>
}
@section Body{
    <div class="container x_panel">
        <div class="row">
            <div class="col-lg-5">
                <h4 style="color:#ff6a00" id="hDept">New Department</h4>
            </div>
        </div>
        <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
        <br />
        <div class="x_title"></div>
        <div class="x_panel">
            <div class="container-fluid">
                <div class="form-group">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtDept" id="txtDept" placeholder="Department Name" />
                        </div>
                        <div class="col-lg-5">
                            <button type="button" class="btn btn-outline-success" id="btnSave">
                                <span class="fa fa-save"></span> Save
                            </button>
                        </div>
                    </div>
                    <br />
                    <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
                </div>
            </div>
        </div>
    </div>

}

Crystel/Areas/HR/Views/Project/ProjectList.cshtml
@model DataAccsess.Entity.vmProject
@{
    ViewBag.Title = "ProjectList";
    Layout = "~/Areas/HR/Views/Shared/View.cshtml";
}
@section Head{
    <script type="text/javascript">
         function Update(id) {
            debugger;
            window.location = '@Url.Action("Update/Id", "Project")'.replace("Id", id)
        }
    </script>
}
@section Body{
    <div class="container x_panel">
        <div class="row">
            <div class="col-lg-5">
                <h4 style="color:#ff6a00">Project List</h4>
            </div>
        </div>
        <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
        <br />
        <div class="x_title"></div>
        <div class="x_panel">
            <div class="container-fluid">
                <div class="form-group">
                    <table class="table">
                        <thead style="background-color:white ; color:#ff6a00;border-color:#ff6a00">
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var x = from a in Model.projects
                                        select a;
                            }
                            @foreach (var y in x)
                            {
                                <tr>
                                    <th scope="row">@y.Name</th>
                                    <td align="right">
                                        <button type="button" class="btn btn-danger" onclick="del(@y.Id)">Delete</button>
                                    </td>
                                    <td align="right">
                                        <button type="button" class="btn btn-warning" onclick="Update(@y.Id)">Edit</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                    <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
                </div>
            </div>
        </div>
    </div>
}

Crystel/Areas/HR/Views/Project/ProjectName.cshtml
@{
    ViewBag.Title = "NewJobTitle";
    Layout = "~/Areas/HR/Views/Shared/View.cshtml";
}
@section Head{
    <script type="text/javascript">
    $(document).ready(function () {
            debugger;
            var Id = @ViewData["Id"];
            if (Id != 0) {
                $('#btnSave').text("Update")
                $('#hProject').text("Edit Project")
                $.ajax({
                    type: 'Get',
                    url: '/CrystelWebApi/api/Project/LoadProject?Id=' + Id,
                    contentType: 'application/json;charset=utf-8',
                    dataType: 'json',
                    data: '{}',
                    success: function (data) {
                        $('#txtProject').val(data.Name);
                    }
                })
            }
            $('#btnSave').click(function () {
                debugger;
                var Id = @ViewData["Id"];
                if (Id != 0) {
                    var name = $("#txtProject").val();
                    var data = {
                        'Id': Id,
                    'Name': name,
                }
                    $.ajax({
                        type: 'post',
                        url: '/CrystelWebApi/api/Project/Update',
                        contentType: 'application/json;charset=utf-8',
                        data: JSON.stringify(data),
                        dataType: 'json',
                        success: function () {
                            alert("Updated")
                        },
                        error: function (error) {
                            alert(error.responseText);
                            alert('there is error');
                        }


                    })
                }
                else {
                    var name = $("#txtProject").val();
                    var data = {
                        'Name': name,
                    }
                    $.ajax({
                        type: 'Post',
                        url: '/CrystelWebApi/api/Project/Save',
                        contentType: 'application/json;charset=utf-8',
                        data: JSON.stringify(data),
                        dataType: 'json',
                        success: function () {
                            alert("Saved")
                        },
                        error: function (error) {
                            alert(error.responseText);
                            alert('there is error');
                        }


                    })
                }

            })

        });
    </script>
}
@section Body{
    <div class="container x_panel">
        <div class="row">
            <div class="col-lg-5">
                <h4 style="color:#ff6a00" id="hProject">New Project</h4>
            </div>
        </div>
        <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
        <br />
        <div class="x_title"></div>
        <div class="x_panel">
            <div class="container-fluid">
                <div class="form-group">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <input type="text" class="form-control" name="txtProject" id="txtProject" placeholder="Project Name" />
                        </div>
                        <div class="col-lg-5">
                            <button type="button" class="btn btn-outline-success" id="btnSave">
                                <span class="fa fa-save"></span> Save
                            </button>
                        </div>
                    </div>
                    <br />
                    <div style="border-radius:1px 3px;border-top:3px solid #ff6a00"></div>
                </div>
            </div>
        </div>
    </div>

}

Crystel/Areas/HR/Views/Shared/View.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style type="text/css">
        input {
            padding: 10px;
            font-family: FontAwesome, "Open Sans", Verdana, sans-serif;
            font-style: normal;
            font-weight: normal;
            text-decoration: inherit;
        }
    </style>
    <link rel="icon" href="~/Image/crystel_social.jpg">
    <!--Styles-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="~/StyleCrystel/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/animate.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/themify-icons.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/flaticon.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/slick.css" rel="stylesheet" />
    <link href="~/StyleCrystel/css/style.css" rel="stylesheet" />
    <script src="~/StyleCrystel/js/jquery-1.12.1.min.js"></script>
    <script src="~/StyleCrystel/js/bootstrap.min.js"></script>
    <script src="~/StyleCrystel/js/popper.min.js"></script>
    <script src="~/StyleCrystel/js/jquery.magnific-popup.js"></script>
    <script src="~/StyleCrystel/js/swiper.min.js"></script>
    <script src="~/StyleCrystel/js/masonry.pkgd.js"></script>
    <script src="~/StyleCrystel/js/owl.carousel.min.js"></script>
    <script src="~/StyleCrystel/js/slick.min.js"></script>
    <script src="~/StyleCrystel/js/custom.js"></script>
    <title>@ViewBag.Title - Crystel</title>
    @RenderSection("Head", false)
</head>
<body>
    <div class="container">
        <header class="main_menu">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <a class="navbar-brand" href="index.html">
                                <img src="~/Image/logo.png" alt="logo" width="220" height="50"/>
                            </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse main-menu-item justify-content-end"
                                 id="navbarSupportedContent">
                                <ul class="navbar-nav">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="index.html">Home </a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Create
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="project.html">New Employee</a>
                                            <a class="dropdown-item" href="project_details.html">New Department</a>
                                            <a class="dropdown-item" href="service.html">New Job Title</a>
                                            <a class="dropdown-item" href="elements.html">New Project Name</a>
                                        </div>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Manage
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="project.html">Employees</a>
                                            <a class="dropdown-item" href="project_details.html">Departments</a>
                                            <a class="dropdown-item" href="service.html">Job Titles</a>
                                            <a class="dropdown-item" href="elements.html">Projects</a>
                                        </div>
                                    </li>
                                    <li class="nav-item active">
                                        <a class="nav-link" href="contact.html">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </header>
    </div>
        
    @RenderSection("Body")
</body>
</html>

Crystel/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>